# -*- coding: utf-8 -*-
"""BubbleSort.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1kZgGlA0B28r4aOj-rQaLbuEoDaHHVBmZ
"""

def bubble_sort(array):
  for i in range(1,len(array)):
    for j in range(len(array)-i):
      if array[j]>array[j+1]:
        temp=array[j]
        array[j]=array[j+1]
        array[j+1]=temp
  return array

numbers=[1,12,3,5,6,1,8,55,8,8,2,17]
print("Sorted array: {}".format(bubble_sort(numbers)))