# -*- coding: utf-8 -*-
"""Quiz_Game.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ylGZDf1PlMtAKedeaE5EG0Zde3EKHxZ3
"""

print("Wlecome to my computer quiz!")

playing=input("Do you want to play?")

if playing.lower()!="yes":
  quit()

print("Okay!Let's play :)")
score=0

answer=input("What does CPU stand for? ")
if answer.lower() == "central processing unit":
  print("Correct!")
  score +=1
else:
  print("Incorrect!")

answer=input("What does GPU stand for? ")
if answer.lower() == "graphic processing unit":
  print("Correct!")
  score +=1
else:
  print("Incorrect!")

answer=input("What does RAM stand for? ")
if answer.lower() == "random access memory":
  print("Correct!")
  score +=1
else:
  print("Incorrect!")

answer=input("What does PSU stand for? ")
if answer.lower() == "power supply":
  print("Correct!")
  score +=1
else:
  print("Incorrect!")

print("You got "+str(score)+" questions correct!")
print("You got "+str((score/4)*100)+"%")